version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db_cafedev_2026
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_cafedev
    ports:
    - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
  
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db_cafedev
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: on-failure
  
  frontend:
    build: ./FrontEnd
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data: